<?php

use Krystal\Widget\GridView\GridViewWidget;
use Krystal\Form\Element;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="btn-toolbar">
    <div class="dropdown">
      <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
        <i class="glyphicon glyphicon-list"></i> <?php $this->show('Menu'); ?>
      </button>

      <div class="dropdown-menu">
         <a class="dropdown-item" href="<?php echo $this->url('Testimonials:Admin:Testimonial@addAction'); ?>"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Add new testimonial'); ?></a>
         <div class="dropdown-divider"></div>
         <div class="dropdown-header"><?php $this->show('Actions'); ?></div>
         <?php if (!empty($testimonials)): ?>
         <a class="dropdown-item" href="#" data-button="save-changes" data-url="<?php echo $this->url('Testimonials:Admin:Testimonial@tweakAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes');?></a>
         <a class="dropdown-item" href="#" data-button="remove-selected" data-url="<?php echo $this->url('Testimonials:Admin:Testimonial@deleteAction', null); ?>"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a>
         <?php else: ?>
         <a class="dropdown-item disabled"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes');?></a>
         <a class="dropdown-item disabled"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a>
         <?php endif; ?>
      </div>
    </div>
</div>

<div class="card">
    <h2><? $this->show('Testimonials'); ?> <small>(<?php echo count($testimonials); ?>)</small></h2>

    <form>
        <div class="table-responsive">
            <?= $this->widget(new GridViewWidget($testimonials, array(
                'batch' => true,
                'pk' => 'id',
                'tableClass' => 'table table-hover table-bordered table-striped',
                'columns' => array(
                    array(
                        'column' => 'id',
                        'label' => '#'
                    ),

                    array(
                        'column' => 'author',
                    ),

                    array(
                        'column' => 'content',
                        'label' => 'Testimonial'
                    ),

                    array(
                        'column' => 'published',
                        'value' => function($testimonial){
                            return Element::checkbox(sprintf('published[%s]', $testimonial->getId()), $testimonial->getPublished());
                        }
                    ),
                    
                    array(
                        'column' => 'order',
                        'value' => function($testimonial){
                            return Element::number(sprintf('order[%s]', $testimonial->getId()), $testimonial->getOrder(), array('class' => 'form-control', 'min' => '0'));
                        }
                    )
                ),

                'actions' => array(
                    'edit' => function($testimonial){
                        return Icon::edit(
                            $this->url('Testimonials:Admin:Testimonial@editAction', $testimonial->getId()),
                            $this->translate('Edit this testimonial')
                        );
                    },

                    'remove' => function($testimonial){
                        return Icon::remove(
                            $this->url('Testimonials:Admin:Testimonial@deleteAction', $testimonial->getId()),
                            $this->translate('Remove this testimonial')
                        );
                    }
                )

            ))); ?>

            <?php if (empty($testimonials)): ?>
            <div class="center-block">
                <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No testimonials'); ?></h2>
            </div>
            <?php endif; ?>
        </div>
    </form>
</div>