<?php

use Krystal\Grid\Grid;
use Krystal\Form\Element;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="btn-toolbar">
	<div class="btn-group">
	  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
		<i class="glyphicon glyphicon-list"></i> <?php $this->show('Menu'); ?> <span class="caret"></span>
	  </button>
	  <ul class="dropdown-menu">
		 <li><a href="<?php echo $this->url('Testimonials:Admin:Testimonial@addAction'); ?>"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Add new testimonial'); ?></a></li>
		 <li class="divider"></li>
		 <li class="dropdown-header"><?php $this->show('Actions'); ?></li>
		 
		 <?php if (!empty($testimonials)): ?>
		 <li><a href="#" data-button="save-changes" data-url="<?php echo $this->url('Testimonials:Admin:Testimonial@tweakAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes');?></a></li>
		 <li><a href="#" data-button="remove-selected" data-url="<?php echo $this->url('Testimonials:Admin:Testimonial@deleteAction', null); ?>"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 <?php else: ?>
		 <li class="disabled"><a><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes');?></a></li>
		 <li class="disabled"><a><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 <?php endif; ?>
		 
	  </ul>
	</div>
</div>

<h2><i class="fa fa-mixcloud"></i> <? $this->show('Testimonials'); ?> <small>(<?php echo count($testimonials); ?>)</small></h2>

<form>
	<div class="table-responsive">
        <?= Grid::render($testimonials, array(
            'batch' => true,
            'pk' => 'id',
            'tableClass' => 'table table-hover table-bordered table-striped table-condensed',
            'columns' => array(
                array(
                    'column' => 'id',
                    'label' => '#'
                ),

                array(
                    'column' => 'author',
                ),

                array(
                    'column' => 'content',
                    'label' => 'Testimonial'
                ),

                array(
                    'column' => 'published',
                    'value' => function($testimonial){
                        return Element::checkbox(sprintf('published[%s]', $testimonial->getId()), $testimonial->getPublished());
                    }
                ),
                
                array(
                    'column' => 'order',
                    'value' => function($testimonial){
                        return Element::number(sprintf('order[%s]', $testimonial->getId()), $testimonial->getOrder(), array('class' => 'form-control', 'min' => '0'));
                    }
                )
            ),

            'actions' => array(
                'edit' => function($testimonial){
                    return Icon::edit(
                        $this->url('Testimonials:Admin:Testimonial@editAction', $testimonial->getId()),
                        $this->translate('Edit this testimonial')
                    );
                },

                'remove' => function($testimonial){
                    return Icon::remove(
                        $this->url('Testimonials:Admin:Testimonial@deleteAction', $testimonial->getId()),
                        $this->translate('Remove this testimonial')
                    );
                }
            )

        ), $this->translator); ?>        
		
		<?php if (empty($testimonials)): ?>
		<div class="center-block">
			<h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No testimonials'); ?></h2>
		</div>
		<?php endif; ?>
	</div>
</form>
