<?php

use Krystal\Form\Element;

?>

<form data-group="testimonial">
	<div class="well clearfix">
        <?php echo Element::hidden('testimonial[id]', $testimonial->getId()); ?>

		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Author'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
                    <?php echo Element::text('testimonial[author]', $testimonial->getAuthor(), array('class' => 'form-control')); ?>
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>

		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Content'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
                    <?php echo Element::textarea('testimonial[content]', $testimonial->getContent(), array('class' => 'form-control')); ?>
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>
    </div>

    <?php if ($testimonial->getId()): ?>

    <button data-button="save" data-url="<?php echo $this->url('Testimonials:Admin:Edit@updateAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
	<button data-button="save-create" data-back-url="<?php echo $this->url('Testimonials:Admin:Add@indexAction'); ?>" data-url="<?php echo $this->url('Testimonials:Admin:Edit@updateAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save & Create new'); ?></button>

	<?php else: ?>

	<button data-button="add" data-back-url="<?php echo $this->url('Testimonials:Admin:Edit@indexAction', null); ?>" data-url="<?php echo $this->url('Testimonials:Admin:Add@addAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
	<button data-button="add-create" data-url="<?php echo $this->url('Testimonials:Admin:Add@addAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add & Create new'); ?></button>

	<?php endif; ?>

	<button data-button="cancel" data-url="<?php echo $this->url('Testimonials:Admin:Browser@indexAction'); ?>" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>

</form>