<?php

use Krystal\Form\Element;
defined('KRYSTAL') or die;

?>

<form data-group="testimonial">
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#testimonial" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Testimonial'); ?></a></li>
        <li role="presentation"><a href="#configuration" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Configuration'); ?></a></li>
	</ul>

    <div class="tab-content">
        <div class="tab-pane fade in active" id="testimonial" role="tabpanel">
            <div class="well">
                <?php echo Element::hidden('testimonial[id]', $testimonial->getId()); ?>

                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Author'); ?></label>
                    <div class="col-lg-10">
                        <div class="input-group">
                            <?php echo Element::text('testimonial[author]', $testimonial->getAuthor(), array('class' => 'form-control', 'placeholder' => $this->translate('Who said this?'))); ?>
                            <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Content'); ?></label>
                    <div class="col-lg-10">
                        <div class="input-group">
                            <?php echo Element::textarea('testimonial[content]', $testimonial->getContent(), array('rows' => '8', 'class' => 'form-control', 'placeholder' => $this->translate('What they said?'))); ?>
                            <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="tab-pane fade in" id="configuration" role="tabpanel">
            <div class="well">
                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Published'); ?></label>
                    <div class="col-lg-10">
                        <div class="input-group">
                            <?php echo Element::checkbox('testimonial[published]', $testimonial->getPublished()); ?>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Order'); ?></label>
                    <div class="col-lg-10">
                        <div class="input-group">
                            <?php echo Element::number('testimonial[order]', $testimonial->getOrder(), array('class' => 'form-control', 'min' => '0', 'placeholder' => $this->translate('Sorting order in the list'))); ?>
                            <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <?php if ($testimonial->getId()): ?>

    <button data-button="save" data-url="<?php echo $this->url('Testimonials:Admin:Testimonial@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
	<button data-button="save-create" data-back-url="<?php echo $this->url('Testimonials:Admin:Testimonial@addAction'); ?>" data-url="<?php echo $this->url('Testimonials:Admin:Testimonial@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save & Create new'); ?></button>

    <?php else: ?>

	<button data-button="add" data-back-url="<?php echo $this->url('Testimonials:Admin:Testimonial@editAction', null); ?>" data-url="<?php echo $this->url('Testimonials:Admin:Testimonial@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
	<button data-button="add-create" data-url="<?php echo $this->url('Testimonials:Admin:Testimonial@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add & Create new'); ?></button>

	<?php endif; ?>

    <button data-button="cancel" data-url="<?php echo $this->url('Testimonials:Admin:Testimonial@gridAction'); ?>" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>
</form>